package ar.gob.malvinas.faltas.core.domain.enums;

public enum DocumentoVariableNamespace {
    ACTA, INFRACTOR, DOMICILIO_INFRACTOR, DOMICILIO_CONSTITUIDO,
    DOMICILIO_INFRACCION, LICENCIA, INFRACCION, JUZGADO,
    DEPENDENCIA, INSPECTOR, FIRMANTE, DOCUMENTO, FALLO,
    PAGO, NOTIFICACION, NOMENCLATURA, UBICACION, SISTEMA
}
