erDiagram
    Acta ||--o{ ActaEvento : tiene
    Acta ||--|| ActaSnapshot : proyecta

    Acta {
        INT8 Id PK
        CHAR36 IdTecnico
        VARCHAR20 NroActa
        SMALLINT TipoActa
        INT IdDep
        SMALLINT VerDep
        INT IdInsp
        SMALLINT VerInsp
        DATETIME FhActa
        CHAR5 IdTcaInfr
        INT AltInfr
        CHAR2 IdLocInfr
        SMALLINT IdBarInfr
        SMALLINT SiDomTxtInfr
        VARCHAR150 DomTxtInfr
        SMALLINT SiEjeUrb
        DECIMAL12_8 LatInfr
        DECIMAL12_8 LonInfr
        DATETIME FhAlta
        CHAR36 IdUserAlta
        LVARCHAR ObsActa
    }

    ActaEvento {
        INT8 Id PK
        INT8 IdActa FK
        DATETIME FhEvento
        SMALLINT TipoEvt
        SMALLINT OrigenEvt
        SMALLINT BloqueFunc
        SMALLINT EstProcAnt
        SMALLINT EstProcNue
        SMALLINT SitAdmAnt
        SMALLINT SitAdmNue
        INT8 IdDocu
        INT8 IdNotif
        CHAR36 IdUserEvt
        SMALLINT SiEvtCierre
        SMALLINT SiEvtExterno
        SMALLINT SiPermReing
    }

    ActaSnapshot {
        INT8 IdActa PK, FK
        DATETIME FhActa
        INT IdDep
        SMALLINT VerDep
        INT IdInsp
        SMALLINT VerInsp
        SMALLINT BloqueActual
        SMALLINT EstProcAct
        SMALLINT SitAdmAct
        VARCHAR40 CodBandeja
        SMALLINT SiVisibleBandeja
        SMALLINT Prioridad
        SMALLINT SiNotifActa
        SMALLINT SiNotifActaProc
        SMALLINT SiNotifActaAcusePend
        SMALLINT SiNotifMedPrev
        SMALLINT SiNotifMedPrevProc
        SMALLINT SiNotifMedPrevAcusePend
        SMALLINT SiNotifFallo
        SMALLINT SiNotifFalloProc
        SMALLINT SiNotifFalloAcusePend
        SMALLINT CantReintNotif
        SMALLINT SiPagoVolunt
        DATETIME FhPagoVolunt
        DECIMAL16_2 MontoActa
        SMALLINT SiPagoTotal
        SMALLINT SiPlanPago
        SMALLINT CantCuotasPlan
        DECIMAL16_2 ValorCuotaPlan
        SMALLINT CantCaidasPlan
        SMALLINT SiGestionExt
        SMALLINT TipoGestionExt
        SMALLINT SiReingresoGestionExt
        SMALLINT ResultadoGestionExt
        DATETIME FhVtoPresentacion
        DATETIME FhVtoApelacion
        DATETIME FhVtoApremio
        INT8 IdEvtUlt
        INT8 IdDocuUlt
        INT8 IdNotifUlt
        DATETIME FhUltMod
        CHAR36 IdUserUltMod
        DATETIME FhSnapshot
    }