erDiagram
    Acta ||--o| ActaTransito : especializa
    Acta ||--o| ActaContravencion : especializa
    Acta ||--o| ActaSustanciasAlimenticias : especializa
    Acta ||--o{ ActaMedidaPreventiva : tiene
    Acta ||--o{ ActaEvidencia : tiene
    Acta ||--o{ ActaArticuloInfringido : aplica
    Acta ||--o{ ActaVehiculo : asocia

    ActaTransito ||--o{ ActaTransitoAlcoholemia : tiene_mediciones

    ActaTransito {
        INT8 IdActa PK, FK
        CHAR8 NroLic
        SMALLINT IdProvLic
        SMALLINT VerProvLic
        INT IdMuniLic
        SMALLINT VerMuniLic
        INT IdDptoLic
        SMALLINT VerDptoLic
        SMALLINT SiRetLic
        SMALLINT SiRetVeh
        SMALLINT SiCtrlAlcoh
        INT IdAlcoholimetro
        SMALLINT VerAlcoholimetro
        SMALLINT TipoPruebaAlcohFin
        SMALLINT CantMedAlcoh
        DECIMAL4_2 ResAlcohFin
        CHAR3 UniMedAlcoh
    }

    ActaTransitoAlcoholemia {
        INT8 Id PK
        INT8 IdActa FK
        SMALLINT OrdenMed
        SMALLINT TipoPrueba
        SMALLINT ResCuali
        DECIMAL4_2 ResNum
        CHAR3 UniMed
        SMALLINT SiResFin
    }

    ActaVehiculo {
        INT8 Id PK
        INT8 IdActa FK
        VARCHAR10 DomVeh
        SMALLINT TipoVeh
        VARCHAR80 TipoVehTxt
        VARCHAR64 MarcaVeh
        VARCHAR128 ModeloVeh
    }

    ActaContravencion {
        INT8 IdActa PK, FK
        SMALLINT IdSuj
        INT IdBie
        SMALLINT Circ
        CHAR2 Secc
        CHAR7 Frac
        CHAR7 Mza
        CHAR7 Parc
        CHAR7 UFun
        CHAR3 UComp
        SMALLINT OrigenNomencl
        SMALLINT IdRub
        SMALLINT VerRub
        SMALLINT AmbitoCtv
        VARCHAR80 AmbitoCtvTxt
    }

    ActaSustanciasAlimenticias {
        INT8 IdActa PK, FK
        SMALLINT IdRub
        SMALLINT VerRub
        SMALLINT AmbitoAct
        VARCHAR80 AmbitoActTxt
    }

    ActaMedidaPreventiva {
        INT8 Id PK
        INT8 IdActa FK
        INT IdMedPrev
        SMALLINT VerMedPrev
        VARCHAR255 MedPrevTxt
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    ActaEvidencia {
        INT8 Id PK
        INT8 IdActa FK
        SMALLINT TipoEvid
        VARCHAR255 StorageKey
        VARCHAR120 NomArchivo
        VARCHAR80 MimeType
        VARCHAR128 HashEvid
        VARCHAR255 ObsEvid
        SMALLINT OrdenEvid
        DATETIME FhCaptura
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    ActaArticuloInfringido {
        INT8 Id PK
        INT8 IdActa FK
        VARCHAR8 IdNorma
        SMALLINT VerNorma
        VARCHAR8 IdArtNorma
        SMALLINT VerArtNorma
        SMALLINT UniMedBase
        INT IdTarifario
        DECIMAL16_2 ValorBase
        SMALLINT UniMedApl
        DECIMAL16_2 ValorApl
        SMALLINT SiActiva
    }