erDiagram
    Acta ||--o{ ActaDocumento : vincula
    Documento ||--o{ ActaDocumento : vincula
    Documento ||--o{ DocumentoFirma : tiene
    Documento ||--o{ DocumentoObservacion : recibe
    Acta ||--o{ Notificacion : tiene
    Documento ||--o{ Notificacion : es_notificado
    Notificacion ||--o{ NotificacionIntento : tiene
    Notificacion ||--o{ NotificacionAcuse : tiene
    Notificacion ||--o{ NotificacionObservacion : recibe

    Documento {
        INT8 IdDocu PK
        SMALLINT TipoDocu
        SMALLINT EstadoDocu
        VARCHAR30 NroDocu
        INT IdTalonario
        SMALLINT TipoFirmaReq
        VARCHAR255 StorageKey
        VARCHAR128 HashDocu
        DATETIME FhGeneracion
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    ActaDocumento {
        INT8 IdActa FK
        INT8 IdDocu FK
        SMALLINT RolDocuActa
        SMALLINT SiPrincipal
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    DocumentoFirma {
        INT8 Id PK
        INT8 IdDocu FK
        SMALLINT TipoFirma
        SMALLINT EstadoFirma
        CHAR36 IdUserFirma
        DATETIME FhSolicitud
        DATETIME FhFirma
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    DocumentoObservacion {
        INT8 Id PK
        INT8 IdDocu FK
        VARCHAR255 ObsDocu
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    Notificacion {
        INT8 IdNotif PK
        SMALLINT TipoNotif
        SMALLINT EstadoNotif
        INT8 IdDocu FK
        INT8 IdActa FK
        DATETIME FhGeneracion
        DATETIME FhEmision
        SMALLINT CanalNotif
        SMALLINT SiRequiereAcuse
        SMALLINT SiAcuseRecibido
        SMALLINT EstadoAcuse
        DATETIME FhAcuse
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    NotificacionIntento {
        INT8 Id PK
        INT8 IdNotif FK
        SMALLINT NroIntento
        SMALLINT CanalNotif
        SMALLINT TipoDestNotif
        VARCHAR150 DestNotif
        SMALLINT EstadoIntento
        DATETIME FhIntento
        DATETIME FhResultado
        VARCHAR255 ResultadoIntento
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    NotificacionAcuse {
        INT8 Id PK
        INT8 IdNotif FK
        INT8 IdIntentoNotif
        SMALLINT TipoAcuse
        SMALLINT EstadoAcuse
        DATETIME FhAcuse
        VARCHAR255 StorageKeyAcuse
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }

    NotificacionObservacion {
        INT8 Id PK
        INT8 IdNotif FK
        VARCHAR255 ObsNotif
        DATETIME FhAlta
        CHAR36 IdUserAlta
    }