-- Secuencias base para Informix 12.10

CREATE SEQUENCE SeqFalActa;
CREATE SEQUENCE SeqFalActEvi;
CREATE SEQUENCE SeqFalActEv;
CREATE SEQUENCE SeqFalObs;
CREATE SEQUENCE SeqFalDep;
CREATE SEQUENCE SeqFalInsp;
CREATE SEQUENCE SeqFalActTrAlc;
CREATE SEQUENCE SeqFalActMedPr;
CREATE SEQUENCE SeqFalTarUni;
CREATE SEQUENCE SeqFalActArtI;
CREATE SEQUENCE SeqFalActArtA;
CREATE SEQUENCE SeqNumPol;
CREATE SEQUENCE SeqNumTal;
CREATE SEQUENCE SeqNumTalMov;
CREATE SEQUENCE SeqFalAlco;
CREATE SEQUENCE SeqRubCom;
CREATE SEQUENCE SeqFalDoc;
CREATE SEQUENCE SeqFalDocFir;
CREATE SEQUENCE SeqFalDocObs;
CREATE SEQUENCE SeqFalNotif;
CREATE SEQUENCE SeqFalNotInt;
CREATE SEQUENCE SeqFalNotAcu;
CREATE SEQUENCE SeqFalNotObs;
CREATE SEQUENCE SeqStorBack;
CREATE SEQUENCE SeqStorPol;