-- 07-tablas-snapshot.sql
-- Generado desde spec/13-ddl

CREATE TABLE FalActaSnapshot
(
    IdActa               INT8 NOT NULL,
    FhActa               DATETIME YEAR TO SECOND NOT NULL,
    IdDep                INT NOT NULL,
    VerDep               SMALLINT NOT NULL,
    IdInsp               INT NOT NULL,
    VerInsp              SMALLINT NOT NULL,
    BloqueActual         SMALLINT NOT NULL,
    EstProcAct           SMALLINT NOT NULL,
    SitAdmAct            SMALLINT NOT NULL,
    CodBandeja           VARCHAR(40) NOT NULL,
    SiVisibleBandeja     SMALLINT NOT NULL,
    Prioridad            SMALLINT,
    SiNotifActa          SMALLINT NOT NULL,
    SiNotifActaProc      SMALLINT NOT NULL,
    SiNotifActaAcusePend SMALLINT NOT NULL,
    SiNotifMedPrev       SMALLINT NOT NULL,
    SiNotifMedPrevProc   SMALLINT NOT NULL,
    SiNotifMedPrevAcusePend SMALLINT NOT NULL,
    SiNotifFallo         SMALLINT NOT NULL,
    SiNotifFalloProc     SMALLINT NOT NULL,
    SiNotifFalloAcusePend SMALLINT NOT NULL,
    CantReintNotif       SMALLINT NOT NULL,
    SiPagoVolunt         SMALLINT NOT NULL,
    FhPagoVolunt         DATETIME YEAR TO SECOND,
    MontoActa            DECIMAL(16,2),
    SiPagoTotal          SMALLINT NOT NULL,
    SiPlanPago           SMALLINT NOT NULL,
    CantCuotasPlan       SMALLINT,
    ValorCuotaPlan       DECIMAL(16,2),
    CantCaidasPlan       SMALLINT NOT NULL,
    SiGestionExt         SMALLINT NOT NULL,
    TipoGestionExt       SMALLINT,
    SiReingresoGestionExt SMALLINT NOT NULL,
    ResultadoGestionExt  SMALLINT,
    FhVtoPresentacion    DATETIME YEAR TO SECOND,
    FhVtoApelacion       DATETIME YEAR TO SECOND,
    FhVtoApremio         DATETIME YEAR TO SECOND,
    IdEvtUlt             INT8,
    IdDocuUlt            INT8,
    IdNotifUlt           INT8,
    FhUltMod             DATETIME YEAR TO SECOND,
    IdUserUltMod         CHAR(36),
    FhSnapshot           DATETIME YEAR TO SECOND NOT NULL,
    CONSTRAINT PkFalSnap PRIMARY KEY (IdActa)
);