-- Foreign keys base para Informix 12.10
-- Nota: se omiten FKs hacia catálogos externos no incluidos en este bloque.
-- Nota: se omiten FalDocumento.StorageKey y FalNotificacionAcuse.StorageKeyAcuse por diferencia de longitud respecto de StorObjeto.StorageKey.

ALTER TABLE FalActa ADD CONSTRAINT FkFalActa_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE FalActa ADD CONSTRAINT FkFalActa_FalInspVer FOREIGN KEY (IdInsp, VerInsp) REFERENCES FalInspectorVersion (IdInsp, VerInsp);
ALTER TABLE FalActaEvidencia ADD CONSTRAINT FkFalActEvi_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaEvidencia ADD CONSTRAINT FkFalActEvi_StorObj FOREIGN KEY (StorageKey) REFERENCES StorObjeto (StorageKey);
ALTER TABLE FalActaEvento ADD CONSTRAINT FkFalActEv_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaEvento ADD CONSTRAINT FkFalActEv_FalDoc FOREIGN KEY (IdDocuRel) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalActaEvento ADD CONSTRAINT FkFalActEv_FalNotif FOREIGN KEY (IdNotifRel) REFERENCES FalNotificacion (IdNotif);
ALTER TABLE FalDependencia ADD CONSTRAINT FkFalDep_FalDep FOREIGN KEY (IdDepPadre) REFERENCES FalDependencia (IdDep);
ALTER TABLE FalDependenciaVersion ADD CONSTRAINT FkFalDepVer_FalDep FOREIGN KEY (IdDep) REFERENCES FalDependencia (IdDep);
ALTER TABLE FalDependenciaVersion ADD CONSTRAINT FkFalDepVer_FalDepVer FOREIGN KEY (IdDepPadre, VerDepPadre) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE FalInspectorVersion ADD CONSTRAINT FkFalInspVer_FalInsp FOREIGN KEY (IdInsp) REFERENCES FalInspector (IdInsp);
ALTER TABLE FalInspectorVersion ADD CONSTRAINT FkFalInspVer_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE FalMedidaPreventiva ADD CONSTRAINT FkFalMedPrev_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE FalActaTransito ADD CONSTRAINT FkFalActTra_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaTransito ADD CONSTRAINT FkFalActTra_FalAlcoVer FOREIGN KEY (IdAlcoholimetro, VerAlcoholimetro) REFERENCES FalAlcoholimetroVersion (IdAlcoholimetro, VerAlcoholimetro);
ALTER TABLE FalActaTransitoAlcoholemia ADD CONSTRAINT FkFalActTrAlc_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaVehiculo ADD CONSTRAINT FkFalActVeh_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaContravencion ADD CONSTRAINT FkFalActCon_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaContravencion ADD CONSTRAINT FkFalActCon_RubComVer FOREIGN KEY (IdRub, VerRub) REFERENCES RubroComVersion (IdRub, VerRub);
ALTER TABLE FalActaSustanciasAlimenticias ADD CONSTRAINT FkFalActSusAl_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaSustanciasAlimenticias ADD CONSTRAINT FkFalActSusAl_RubComVer FOREIGN KEY (IdRub, VerRub) REFERENCES RubroComVersion (IdRub, VerRub);
ALTER TABLE FalActaMedidaPreventiva ADD CONSTRAINT FkFalActMedPr_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaMedidaPreventiva ADD CONSTRAINT FkFalActMedPr_FalMedPrev FOREIGN KEY (IdMedPrev, VerMedPrev) REFERENCES FalMedidaPreventiva (IdMedPrev, VerMedPrev);
ALTER TABLE FalArticuloNormativaFaltas ADD CONSTRAINT FkFalArtNorm_FalNormFal FOREIGN KEY (IdNorma, VerNorma) REFERENCES FalNormativaFaltas (IdNorma, VerNorma);
ALTER TABLE FalActaArticuloInfringido ADD CONSTRAINT FkFalActArtI_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaArticuloInfringido ADD CONSTRAINT FkFalActArtI_FalArtNorm FOREIGN KEY (IdNorma, VerNorma, IdArtNorma, VerArtNorma) REFERENCES FalArticuloNormativaFaltas (IdNorma, VerNorma, IdArtNorma, VerArtNorma);
ALTER TABLE FalActaArticuloInfringido ADD CONSTRAINT FkFalActArtI_FalTarUni FOREIGN KEY (IdTarifario) REFERENCES FalTarifarioUnidadFaltas (IdTarifario);
ALTER TABLE FalActaArticuloAuditoria ADD CONSTRAINT FkFalActArtA_FalActArtI FOREIGN KEY (IdActaArt) REFERENCES FalActaArticuloInfringido (Id);
ALTER TABLE NumTalonario ADD CONSTRAINT FkNumTal_NumPol FOREIGN KEY (IdPolNum) REFERENCES NumPolitica (IdPolNum);
ALTER TABLE NumTalonarioDependencia ADD CONSTRAINT FkNumTalDep_NumTal FOREIGN KEY (IdTalonario) REFERENCES NumTalonario (IdTalonario);
ALTER TABLE NumTalonarioDependencia ADD CONSTRAINT FkNumTalDep_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE NumTalonarioInspector ADD CONSTRAINT FkNumTalIns_NumTal FOREIGN KEY (IdTalonario) REFERENCES NumTalonario (IdTalonario);
ALTER TABLE NumTalonarioInspector ADD CONSTRAINT FkNumTalIns_FalInspVer FOREIGN KEY (IdInsp, VerInsp) REFERENCES FalInspectorVersion (IdInsp, VerInsp);
ALTER TABLE NumTalonarioMovimiento ADD CONSTRAINT FkNumTalMov_NumTal FOREIGN KEY (IdTalonario) REFERENCES NumTalonario (IdTalonario);
ALTER TABLE NumTalonarioMovimiento ADD CONSTRAINT FkNumTalMov_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE NumTalonarioMovimiento ADD CONSTRAINT FkNumTalMov_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE NumTalonarioMovimiento ADD CONSTRAINT FkNumTalMov_FalInspVer FOREIGN KEY (IdInsp, VerInsp) REFERENCES FalInspectorVersion (IdInsp, VerInsp);
ALTER TABLE FalAlcoholimetroVersion ADD CONSTRAINT FkFalAlcoVer_FalAlco FOREIGN KEY (IdAlcoholimetro) REFERENCES FalAlcoholimetro (IdAlcoholimetro);
ALTER TABLE RubroComVersion ADD CONSTRAINT FkRubComVer_RubCom FOREIGN KEY (IdRub) REFERENCES RubroCom (IdRub);
ALTER TABLE FalDocumento ADD CONSTRAINT FkFalDoc_NumTal FOREIGN KEY (IdTalonario) REFERENCES NumTalonario (IdTalonario);
ALTER TABLE FalActaDocumento ADD CONSTRAINT FkFalActDoc_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaDocumento ADD CONSTRAINT FkFalActDoc_FalDoc FOREIGN KEY (IdDocu) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalDocumentoFirma ADD CONSTRAINT FkFalDocFir_FalDoc FOREIGN KEY (IdDocu) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalDocumentoObservacion ADD CONSTRAINT FkFalDocObs_FalDoc FOREIGN KEY (IdDocu) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalNotificacion ADD CONSTRAINT FkFalNotif_FalDoc FOREIGN KEY (IdDocu) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalNotificacion ADD CONSTRAINT FkFalNotif_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalNotificacionIntento ADD CONSTRAINT FkFalNotInt_FalNotif FOREIGN KEY (IdNotif) REFERENCES FalNotificacion (IdNotif);
ALTER TABLE FalNotificacionAcuse ADD CONSTRAINT FkFalNotAcu_FalNotif FOREIGN KEY (IdNotif) REFERENCES FalNotificacion (IdNotif);
ALTER TABLE FalNotificacionAcuse ADD CONSTRAINT FkFalNotAcu_FalNotInt FOREIGN KEY (IdIntentoNotif) REFERENCES FalNotificacionIntento (Id);
ALTER TABLE FalNotificacionObservacion ADD CONSTRAINT FkFalNotObs_FalNotif FOREIGN KEY (IdNotif) REFERENCES FalNotificacion (IdNotif);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalActa FOREIGN KEY (IdActa) REFERENCES FalActa (Id);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalDepVer FOREIGN KEY (IdDep, VerDep) REFERENCES FalDependenciaVersion (IdDep, VerDep);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalInspVer FOREIGN KEY (IdInsp, VerInsp) REFERENCES FalInspectorVersion (IdInsp, VerInsp);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalActEv FOREIGN KEY (IdEvtUlt) REFERENCES FalActaEvento (Id);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalDoc FOREIGN KEY (IdDocuUlt) REFERENCES FalDocumento (IdDocu);
ALTER TABLE FalActaSnapshot ADD CONSTRAINT FkFalSnap_FalNotif FOREIGN KEY (IdNotifUlt) REFERENCES FalNotificacion (IdNotif);
ALTER TABLE StorPolitica ADD CONSTRAINT FkStorPol_StorBack FOREIGN KEY (IdStorageBackend) REFERENCES StorBackend (IdStorageBackend);
ALTER TABLE StorObjeto ADD CONSTRAINT FkStorObj_StorBack FOREIGN KEY (IdStorageBackend) REFERENCES StorBackend (IdStorageBackend);