-- Índices estructurales mínimos

CREATE UNIQUE INDEX UxFalActa01 ON FalActa (IdTecnico);
CREATE UNIQUE INDEX UxFalActa02 ON FalActa (NroActa);
CREATE UNIQUE INDEX UxFalActTrAlc01 ON FalActaTransitoAlcoholemia (IdActa, OrdenMed);
CREATE UNIQUE INDEX UxNumTal01 ON NumTalonario (CodTalonario);
CREATE UNIQUE INDEX UxNumTalMov01 ON NumTalonarioMovimiento (IdTalonario, NroUsado);
CREATE UNIQUE INDEX UxFalAlco01 ON FalAlcoholimetro (CodAlcoholimetro);
CREATE UNIQUE INDEX UxFalAlco02 ON FalAlcoholimetro (NroSerie);
CREATE UNIQUE INDEX UxFalNotInt01 ON FalNotificacionIntento (IdNotif, NroIntento);

CREATE INDEX IxFalActa01 ON FalActa (IdDep, VerDep);
CREATE INDEX IxFalActa02 ON FalActa (IdInsp, VerInsp);
CREATE INDEX IxFalActEvi01 ON FalActaEvidencia (IdActa);
CREATE INDEX IxFalActEvi02 ON FalActaEvidencia (StorageKey);
CREATE INDEX IxFalActEv01 ON FalActaEvento (IdActa);
CREATE INDEX IxFalActEv02 ON FalActaEvento (IdDocuRel);
CREATE INDEX IxFalActEv03 ON FalActaEvento (IdNotifRel);
CREATE INDEX IxFalDep01 ON FalDependencia (IdDepPadre);
CREATE INDEX IxFalDepVer01 ON FalDependenciaVersion (IdDepPadre, VerDepPadre);
CREATE INDEX IxFalInspVer01 ON FalInspectorVersion (IdDep, VerDep);
CREATE INDEX IxFalMedPrev01 ON FalMedidaPreventiva (IdDep, VerDep);
CREATE INDEX IxFalActTra01 ON FalActaTransito (IdAlcoholimetro, VerAlcoholimetro);
CREATE INDEX IxFalActTrAlc01 ON FalActaTransitoAlcoholemia (IdActa);
CREATE INDEX IxFalActCon01 ON FalActaContravencion (IdRub, VerRub);
CREATE INDEX IxFalActSusAl01 ON FalActaSustanciasAlimenticias (IdRub, VerRub);
CREATE INDEX IxFalActMedPr01 ON FalActaMedidaPreventiva (IdActa);
CREATE INDEX IxFalActMedPr02 ON FalActaMedidaPreventiva (IdMedPrev, VerMedPrev);
CREATE INDEX IxFalActArtI01 ON FalActaArticuloInfringido (IdActa);
CREATE INDEX IxFalActArtI02 ON FalActaArticuloInfringido (IdNorma, VerNorma, IdArtNorma, VerArtNorma);
CREATE INDEX IxFalActArtI03 ON FalActaArticuloInfringido (IdTarifario);
CREATE INDEX IxFalActArtA01 ON FalActaArticuloAuditoria (IdActaArt);
CREATE INDEX IxNumTal01 ON NumTalonario (IdPolNum);
CREATE INDEX IxNumTalDep01 ON NumTalonarioDependencia (IdDep, VerDep);
CREATE INDEX IxNumTalIns01 ON NumTalonarioInspector (IdInsp, VerInsp);
CREATE INDEX IxNumTalMov01 ON NumTalonarioMovimiento (IdTalonario);
CREATE INDEX IxNumTalMov02 ON NumTalonarioMovimiento (IdActa);
CREATE INDEX IxNumTalMov03 ON NumTalonarioMovimiento (IdDep, VerDep);
CREATE INDEX IxNumTalMov04 ON NumTalonarioMovimiento (IdInsp, VerInsp);
CREATE INDEX IxFalDoc01 ON FalDocumento (IdTalonario);
CREATE INDEX IxFalActDoc01 ON FalActaDocumento (IdDocu);
CREATE INDEX IxFalDocFir01 ON FalDocumentoFirma (IdDocu);
CREATE INDEX IxFalDocObs01 ON FalDocumentoObservacion (IdDocu);
CREATE INDEX IxFalNotif01 ON FalNotificacion (IdDocu);
CREATE INDEX IxFalNotif02 ON FalNotificacion (IdActa);
CREATE INDEX IxFalNotInt01 ON FalNotificacionIntento (IdNotif);
CREATE INDEX IxFalNotAcu01 ON FalNotificacionAcuse (IdNotif);
CREATE INDEX IxFalNotAcu02 ON FalNotificacionAcuse (IdIntentoNotif);
CREATE INDEX IxFalNotObs01 ON FalNotificacionObservacion (IdNotif);
CREATE INDEX IxFalSnap01 ON FalActaSnapshot (IdDep, VerDep);
CREATE INDEX IxFalSnap02 ON FalActaSnapshot (IdInsp, VerInsp);
CREATE INDEX IxFalSnap03 ON FalActaSnapshot (IdEvtUlt);
CREATE INDEX IxFalSnap04 ON FalActaSnapshot (IdDocuUlt);
CREATE INDEX IxFalSnap05 ON FalActaSnapshot (IdNotifUlt);
CREATE INDEX IxStorPol01 ON StorPolitica (IdStorageBackend);
CREATE INDEX IxStorObj01 ON StorObjeto (IdStorageBackend);